### ISSUE TITLE
Flaky test in "pageObjectModel.test.js"

### ISSUE THREAD

**Issue by vaidasmaciulis** [devbridge/test-juggler#74]
pageObjectModel.test.js has a flaky test. Fails sporadically with error:

```
  ● Example › should access an element defined directly in page

    expect(received).resolves.toBeTruthy()

    Received: false

      21 |         await HomePage.FeedBackLink.click();
      22 |         console.log("Clicked on feedback link");
    > 23 |         await expect(FeedbackPage.TitleText.exists()).resolves.toBeTruthy();
         |                                                                ^
      24 |     });
      25 | });
      26 | }

      at Object.toBeTruthy (node_modules/expect/build/index.js:198:20)
      at Object.<anonymous> (example/tests/pageObjectModel.test.js:23:64)
```

**Comment by jevgenijusmarinuskinas** [comment]
Unable to reproduce currently, both with headless=false and headless=true. Additional waiters does not seem to be needed, because one is already included into exists() method. shortTimeout could be increased in the configuration.
